### ISSUE TITLE
Use bare functions instead of a closure

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Manishearth/mitosis#5]
Is there any reason why `mitosis::spawn()` is generic over `F: FnOnce(A) -> R` instead of just accepting a `fn(A) -> R`? 

A closure that doesn't capture any variables will be coerced to a bare function ([RFC](https://github.com/rust-lang/rfcs/blob/master/text/1558-closure-to-fn-coercion.md)), allowing you to remove [the no capturing invariant](https://github.com/Manishearth/mitosis/blob/bea146873677f7d469425b6054ca6d40599eff7d/src/lib.rs#L79-L80).

**Comment by Manishearth** [comment]
Yes, this is intentional, it used to work the other way until https://github.com/Manishearth/mitosis/commit/5ab38647927a74f4a46c0ca5a5cae99835940437.

If the bare function is dynamically loaded I can't protect against relocations or anything. If there were a way I could only accept function items and not function pointers, I would, but right now there is no generic way to refer to only function item types.
